name: zad_mobile_pos
description: ZAD Mobile POS - Professional Sales & Inventory Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  mobile_scanner: ^3.5.5
  image_picker: ^1.0.7
  esc_pos_printer_plus: any
  esc_pos_utils_plus: any
  network_info_plus: ^4.1.0
  permission_handler: ^11.0.1
  local_auth: ^2.1.8
  crypto: ^3.0.3
  encrypt: ^5.0.1
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  fl_chart: ^0.66.0
  pdf: ^3.8.4
  printing: ^5.11.1
  share_plus: ^7.2.1
  excel: ^4.0.2
  csv: ^5.1.1
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  uuid: ^4.2.1
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1

flutter:
  uses-material-design: true
  generate: true
